### PR TITLE
add  David Doston as maintainer [skip ci]

### PR DESCRIPTION
**Pull request by kain88-de**
@dotsdl Are you OK if I add you as an official maintainer?

### CODE REVIEW

**Comment by kain88-de** [comment]
@conda-forge/core are they build fails because this package still needs an updated conda-smithy?

Since I've just added a maintainer name there shouldn't be big issues.

**Comment by scopatz** [comment]
you probably need to rerender

**Comment by kain88-de** [comment]
@scopatz how do I do the rerender? So far that always happened automatically for other recipes.

**Comment by scopatz** [comment]
you need to install conda-smithy and then run "conda smithy rerender" in the repo.

**Comment by jakirkham** [comment]
ref: https://github.com/conda-forge/conda-smithy/blob/master/README.md#re-rendering-an-existing-feedstock

**Comment by kain88-de** [comment]
@dotsdl ping

**Comment by dotsdl** [comment]
@kain88-de I'm good to do that. Please add me.

**Pull request merged**
